version: "3.8"
services:
  website:
    image: dialgmbh/gldf-website
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy-data:/data
  watchtower:
    image: containrrr/watchtower:1.5.3
    command: gldf_website_1
    restart: always
    environment:
     - WATCHTOWER_POLL_INTERVAL=300
     - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock      

volumes:
  caddy-data: